SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
SCREEN_TITLE = "Plane"
SCREEN_RESIZABLE = True

PLAYER_MOUVEMENT = 0.8  # player's speed
PLAYER_IMAGE = 'images/397518.png'
PLAYER_IMAGE_SCALING = 0.4

LAND_IMAGE = 'images/grassHalf_mid.webp'
LAND_RANGE = 72
LAND_SCALE = 0.5
